let hellfrost = [
	{
        song_name: "Inherit the Earth",
        song_url: "",
        song_length_min: 4,
        song_length_tenth_sec: 4,
        song_length_sec: 6,
        song_length_in_sec: 4*60 + 4*10 + 6,
        song_lyrics: "",
        song_num: 0
    }, 
    {
        song_name: "Phoenix Down",
        song_url: "",
        song_length_min: 3,
        song_length_tenth_sec: 3,
        song_length_sec: 3,
        song_length_in_sec: 3*60 + 3*10 + 3,
        song_lyrics: "",
        song_num: 1
    },
	{
        song_name: "Betrayer of the Code",
        song_url: "",
        song_length_min: 5,
        song_length_tenth_sec: 0,
        song_length_sec: 5,
        song_length_in_sec: 5*60 + 0*10 + 5,
        song_lyrics: "",
        song_num: 2
    }, 
    {
        song_name: "My Own Death",
        song_url: "",
        song_length_min: 4,
        song_length_tenth_sec: 0,
        song_length_sec: 1,
        song_length_in_sec: 4*60 + 0*10 + 1,
        song_lyrics: "",
        song_num: 3
    },
	{
        song_name: "Serenade of Guilt",
        song_url: "",
        song_length_min: 4,
        song_length_tenth_sec: 3,
        song_length_sec: 3,
        song_length_in_sec: 4*60 + 3*10 + 3,
        song_lyrics: "",
        song_num: 4
    },
	{
        song_name: "Collapse My Dream (lyrics)",
        song_url: "Hellfrost/collapse_my_dream.mp3",
        song_length_min: 4,
        song_length_tenth_sec: 1,
        song_length_sec: 5,
        song_length_in_sec: 4*60 + 1*10 + 5,
        song_num: 5,
        song_lyrics: [  25, "Back again, veterans of the same war",
                        29, "Fighting compact darkness", 
                        31, "While we wish upon the black star", 
                        34, "Man never seems to change", 
                        36, "If you know one you know them all",
                        39, "Just collect your heart and run for higher ground",
                        45, "(We arm) we arm ourselves with all that we've been through",
                        50, "While we watch the sun rain down on you",
                        54, "Your only mistake was to let me live",
                        60, "My mind is now a stronghold no one shall enter",
                        65, "And you can't blind what already can't see",
                        73, "Now I channel all my pain to you",
                        75, "Don't speak to me, Don't speak to me as if I can be wrong",
                        80, "Some wounds are not, Some wounds are not meant to heal at all",
                        86, "You'll make the same, You'll make the same mistakes all over again",
                        91, "Stick to your guns and fight for what you are",
                        98, "Tried to put myself in the wrong place at the wrong moment",
                        104, "But there's no power under God that can break me",
                        109, "Everything I hate in this world I find in you",
                        114, "There's a six hundred sixteen reasons not to care",
                        119, "Your only mistake was to let me live",
                        124, "My mind is now a stronghold no one shall enter",
                        129, "And you can't blind what already can't see",
                        137, "Now I channel all my pain to you",
                        140, "Don't speak to me, Don't speak to me as if I can be wrong",
                        145, "Some wounds are not, Some wounds are not meant to heal at all",
                        150, "You'll make the same, You'll make the same mistakes all over again",
                        156, "Stick to your guns and fight for what you are",
                        162, "",
                        178, "No one comes to love pain, No one comes to love pain",
                        188, "No one comes to love pain, we can only hope to endure it",
                        193, "No one comes to love pain, we can only hope to endure it",
                        201, "Don't speak to me, Don't speak to me as if I can be wrong",
                        206, "Some wounds are not, Some wounds are not meant to heal at all",
                        211, "You'll make the same, You'll make the same mistakes all over again",
                        217, "Stick to your guns and fight for what you are",
                        221, "Don't speak to me, Don't speak to me, I can't be wrong",
                        227, "You'll make the same, You'll make the same, The same mistakes again",
                        232, "Stick to your guns, Stick to your guns, And fight for what you are"
                     ]
    },
	{
        song_name: "Green Eyed Demon",
        song_url: "",
        song_length_min: 4,
        song_length_tenth_sec: 2,
        song_length_sec: 3,
        song_length_in_sec: 4*60 + 2*10 + 3,
        song_lyrics: "",
        song_num: 6
    },
	
	{
        song_name: "Iceheart Fragment",
        song_url: "",
        song_length_min: 4,
        song_length_tenth_sec: 2,
        song_length_sec: 9,
        song_length_in_sec: 4*60 + 2*10 + 9,
        song_lyrics: "",
        song_num: 7
    },
	{
        song_name: "Pathfinder",
        song_url: "",
        song_length_min: 4,
        song_length_tenth_sec: 4,
        song_length_sec: 4,
        song_length_in_sec: 4*60 + 4*10 + 4,
        song_lyrics: "",
        song_num: 8
    },
	{
        song_name: "Where the Frost Rose Withers",
        song_url: "",
        song_length_min: 5,
        song_length_tenth_sec: 0,
        song_length_sec: 3,
        song_length_in_sec: 5*60 + 0*10 + 3,
        song_lyrics: "",
        song_num: 9
    }
];
